import type { AiExplanation } from '../types';

type Props = {
  explanation: AiExplanation | null;
  loading: boolean;
  error: string | null;
};

export function AiExplanationPanel({ explanation, loading, error }: Props) {
  if (loading) return <section><p>Loading analysis...</p></section>;
  if (error) return <section><p>Analysis unavailable: {error}</p></section>;
  if (!explanation) return null;

  const isAi = explanation.aiGenerated;

  return (
    <section>
      <h2>
        {isAi ? 'AI Explanation' : 'Analysis Summary'}
        <small> · Provider: {explanation.provider} · {isAi ? 'AI-generated' : 'Deterministic'}</small>
      </h2>

      <p className="analysis-note">
        {isAi
          ? 'ⓘ Generated by Gemini AI. Treat as supplementary to the deterministic RCA findings below.'
          : '⚠ Generated deterministically from RCA findings. The evidence and findings below are the source of truth.'}
      </p>

      <h3>Summary</h3>
      <p>{explanation.summary}</p>

      <h3>Root Cause</h3>
      <p>{explanation.rootCauseSummary}</p>

      <h3>Recommended Action</h3>
      <p>{explanation.recommendedAction}</p>
    </section>
  );
}
